### PR TITLE
Fix jbuilder rule in case of missing binaries

### LINKED ISSUE #170: jbuilder rules doesn't work when odoc is missing
For example:
```
 [rgrinberg:~/reps/ml/ocaml-cohttp] master 1 ± jbuilder rules
Error: Program odoc not found in the tree or in PATH (context: default)
Hint: opam install odoc
```

### PR DESCRIPTION
**Pull request by rgrinberg**
It would be nice to do this without modifying Prog_spec.

Fix #170

### CODE REVIEW

**Comment by rgrinberg** [comment]
Some input from @dra27 and @bobot on how to get this up to snuff would be appreciated.

File: src/build.ml [hunk 1]
```diff
@@ -195,9 +196,11 @@ let files_recursively_in ~dir ~file_tree =
 let store_vfile spec = Store_vfile spec
 
 let get_prog (prog : _ Prog_spec.t) =
+  let open Action.Maybe_prog in
   match prog with
-  | Dep p -> path p >>> arr (fun _ -> p)
-  | Dyn f -> arr f >>> dyn_paths (arr (fun x -> [x]))
+  | Missing s -> arr (fun _ -> Not_found (try s.fail () with e -> e))
+  | Dep p -> path p >>> arr (fun _ -> Found p)
+  | Dyn f -> arr f >>> dyn_paths (arr (fun x -> [x])) >>^ (fun x -> Found x)
```
Comment (bobot) [inline src/build.ml]: @rgrinberg Could you without changing `Prog_spec`, just catch the error when running `f` in the Dyn case ? Something like:

```
| Dyn f -> arr (try Found (f ()) with e -> Not_found e) >>> dyn_paths (arr (function Not_found _ -> [] | Found x -> [x]))
```

**Comment by rgrinberg** [comment]
Thanks @bobot I've implemented your suggestion. Works like a charm.

**Comment by rgrinberg** [comment]
@bobot please have another look. I've had a private exchange with Jeremie where he gave me some feedback about this question:

    Regarding your first question, I think this code could be refactored a
    bit. The sole use of Prog_spec.Dyn is now to encode errors, which are
    always resolution errors. I think we should replace Build.Prog_spec by
    something like this, that we could use as well instead of
    Action.Maybe_prog:

    module Prog : sig
      module Not_found : sig
        type t =
          { context : string
          ; program : string
          ; hint    : string option
          }
      end

      type t = (Path.t, Not_found.t) result
    end

    This has a few advantages:
    - when dumping the rules as a Makefile, we could choose to print
    resolution errors as just the program name and let the shell complain
    - the to/of sexp functions are better defined, in particular they
    round-trip properly
    BTW, I think that [Found <path>] or [Ok <path>] should just be
    serialized as [<path>] rather that [(ok <path>)] or [(found <path>)],
    since this is the common case and there is no ambiguity. This will
    simplify the produced s-expressions.

    Note that I omitted [in_the_tree : bool] in [Not_found.t]. This
    parameter is not very useful and could be removed as well, by assuming
    that it is always [true]. Currently we only set it to [false] when
    looking for the C compiler. But there is no harm in setting to [true]
    in this case as well, if a user tries to install a [gcc] program,
    they'll have other issues.

**Comment by rgrinberg** [comment]
This PR is going up in priority as otherwise it's going to create more conflicts for the cross compilation branch. Some I will request some additional review resources from @dra27

File: src/super_context.mli [hunk 2]
```diff
@@ -58,19 +58,17 @@ val rules : t -> Build_interpret.Rule.t list
 
 val sources_and_targets_known_so_far : t -> src_path:Path.t -> String_set.t
 
-(** [prog_spec t ?hint ?in_the_tree name] resolve a program. If [in_the_tree] is [true]
-    (the default), [name] is looked up in the workspace. Otherwise, or if it is not found
-    in the tree is is looked up in the PATH. If it is not found at all, the resulting
-    [Prog_spec.t] will fail when evaluated.
+(** [prog_spec t ?hint name] resolve a program. [name] is looked up in the
+    workspace, if it is not found in the tree is is looked up in the PATH. If it
+    is not found at all, the resulting [Prog_spec.t] will fail when evaluated.
```
Comment (bobot) [inline src/super_context.mli]: `Prog_spec.t`  -> `Action.Prog.t` and perhaps fail when evaluated is not correct anymore.

File: src/action.mli [hunk 3]
```diff
@@ -14,8 +14,22 @@ end
...
+    type t =
+      { context: string
+      ; program: string
+      ; hint: string option
+      }
+
+    val raise : t -> _
+  end
+
+  type t = (Path.t, Not_found.t) result
```
Comment (bobot) [inline src/action.mli]: Something like `(** result of the lookup of a program, the path to it or informations about the failure to find it *)`
