### PR TITLE
Report better errors for globs pointing to non-existing directories

### LINKED ISSUE #412: problem with glob
I met a problem with the following `jbuild` file on 1.0+beta16. I tried to have some file re-generated whenever a source file (in `src/`) changes, but I got this:

```
jbuilder runtest --no-buffer
Internal error, please report upstream including the contents of _build/log.
Description: Build.get_glob_result_exn: got unevaluated
Backtrace:
Raised at file "src/import.ml", line 19, characters 43-65
Called from file "src/build_system.ml", line 272, characters 16-33
Called from file "src/build_system.ml", line 259, characters 8-25
Called from file "src/build_system.ml", line 273, characters 16-33
Called from file "src/build_system.ml", line 259, characters 8-25
Called from file "src/build_system.ml", line 259, characters 8-25
Called from file "src/build_system.ml", line 259, characters 8-25
Called from file "src/build_system.ml", line 259, characters 8-25
Called from file "src/build_system.ml", line 306, characters 17-47
Called from file "src/build_system.ml" (inlined), line 444, characters 4-30
Called from file "src/future.ml", line 88, characters 40-45
Called from file "src/future.ml", line 93, characters 8-12
```

here is the jbuild file:

```sh
% cat qtest/jbuild 

(rule
  ((targets (run_qtest.ml))
   (deps ((file Makefile) (glob_files ../src/**/*.ml{,i})))
   (fallback)
   ;(libraries (qtest qcheck))
   (action
     (run make qtest-gen))
  ))

(executable
  ((name run_qtest)
   (libraries (sequence gen qcheck containers containers.unix
               containers.data containers.thread containers.iter
               containers.sexp))
  ))

(alias
 ((name    runtest)
  (deps    (run_qtest.exe))
  (action  (run ${<}))
  ))
```

content of `_build/log`:

```
# jbuilder runtest --no-buffer
# OCAMLPARAM: unset
# Workspace root: /home/simon/workspace/containers
$ /home/simon/.opam/4.05.0+flambda/bin/ocamlfind printconf path > /tmp/jbuildff5038.output
$ /home/simon/.opam/4.05.0+flambda/bin/ocamlc.opt -config > /tmp/jbuildc0066a.output
# Jbuilder context:
#  ((name default)
#   (kind default)
#   (merlin true)
#   (for_host ())
#   (build_dir _build/default)
#   (toplevel_path (/home/simon/.opam/4.05.0+flambda/lib/toplevel))
#   (ocaml_bin /home/simon/.opam/4.05.0+flambda/bin)
#   (ocaml /home/simon/.opam/4.05.0+flambda/bin/ocaml)
#   (ocamlc /home/simon/.opam/4.05.0+flambda/bin/ocamlc.opt)
#   (ocamlopt (/home/simon/.opam/4.05.0+flambda/bin/ocamlopt.opt))
#   (ocamldep /home/simon/.opam/4.05.0+flambda/bin/ocamldep.opt)
#   (ocamlmklib /home/simon/.opam/4.05.0+flambda/bin/ocamlmklib.opt)
#   (env ())
#   (findlib_path (/home/simon/.opam/4.05.0+flambda/lib))
#   (arch_sixtyfour true)
#   (natdynlink_supported true)
#   (opam_vars ())
#   (ocamlc_config
#    ((architecture amd64)
#     (asm as)
#     (asm_cfi_supported true)
#     (ast_impl_magic_number Caml1999M020)
#     (ast_intf_magic_number Caml1999N018)
#     (bytecomp_c_compiler
#      "gcc -O2 -fno-strict-aliasing -fwrapv -D_FILE_OFFSET_BITS=64 -D_REENTRANT -fPIC")
#     (bytecomp_c_libraries "-lm  -ldl -lcurses -lpthread                  ")
#     (cc_profile -pg)
#     (ccomp_type cc)
#     (cma_magic_number Caml1999A012)
#     (cmi_magic_number Caml1999I021)
#     (cmo_magic_number Caml1999O011)
#     (cmt_magic_number Caml2012T009)
#     (cmx_magic_number Caml1999Y016)
#     (cmxa_magic_number Caml1999Z015)
#     (cmxs_magic_number Caml2007D002)
#     (default_executable_name a.out)
#     (exec_magic_number Caml1999X011)
#     (ext_asm .s)
#     (ext_dll .so)
#     (ext_exe "")
#     (ext_lib .a)
#     (ext_obj .o)
#     (flambda true)
#     (host x86_64-unknown-linux-gnu)
#     (int_size 63)
#     (model default)
#     (native_c_compiler
#      "gcc -O2 -fno-strict-aliasing -fwrapv -D_FILE_OFFSET_BITS=64 -D_REENTRANT")
#     (native_c_libraries "-lm  -ldl")
#     (native_pack_linker "ld -r  -o ")
#     (os_type Unix)
#     (profiling true)
#     (ranlib ranlib)
#     (safe_string false)
#     (spacetime false)
#     (standard_library /home/simon/.opam/4.05.0+flambda/lib/ocaml)
#     (standard_library_default /home/simon/.opam/4.05.0+flambda/lib/ocaml)
#     (standard_runtime /home/simon/.opam/4.05.0+flambda/bin/ocamlrun)
#     (system linux)
#     (systhread_supported true)
#     (target x86_64-unknown-linux-gnu)
#     (version 4.05.0)
#     (with_frame_pointers false)
#     (word_size 64)))
#   (which
#    ((ocamlc (/home/simon/.opam/4.05.0+flambda/bin/ocamlc.opt))
#     (ocamlfind (/home/simon/.opam/4.05.0+flambda/bin/ocamlfind)))))
```

### PR DESCRIPTION
**Pull request by diml**
Fix #412

### CODE REVIEW

File: src/build_interpret.ml [hunk 1]
```diff
@@ -42,9 +42,13 @@ let static_deps t ~all_targets_by_dir =
...
         | G_evaluated l ->
           { acc with action_deps = Pset.union acc.action_deps (Pset.of_list l) }
-        | G_unevaluated (dir, re) ->
+        | G_unevaluated (loc, dir, re) ->
           match Pmap.find dir (Lazy.force all_targets_by_dir) with
-          | None -> acc
+          | None ->
+            Loc.warn loc "Directory %s doesn't exist."
+              (Path.to_string_maybe_quoted dir);
+            state := G_evaluated [];
```
Comment (rgrinberg) [inline src/build_interpret.ml]: Did this mean that the non-existent glob would be executed more than once? So it's a bit more than just better error reporting?

Comment (diml) [reply src/build_interpret.ml]: It's not documented, but `static_deps` is assumed to turn all the `Paths_glob` from `G_unevaluated` to `G_evaluated`. It wasn't done in this branch and it was a mistake
